#!/usr/bin/env perl
#
# doc_coverage.pl - Generate a machine-readable coverage table (YAML) of the
#   LoC/PCC rule set's test coverage against the reference document.
#
# The reference document ("Revised Final Report PCC ISBD and MARC Task Group,
# October 2016", isbdmarc2016.txt) contains per-field "Current:"/"Future:"
# example pairs. Our test suite carries a '# render:' marker (with a
# [doc ...]/[LoC ...]/[constructed] provenance token) per example it
# implements. This script reads those markers -- the SINGLE SOURCE OF TRUTH --
# and emits a machine-readable YAML table so that "have we covered every
# documented example?" becomes a queryable, diff-able statement rather than a
# manual claim.
#
#   Provenance kinds (from the marker token):
#     doc          - drawn verbatim (or '- derived') from the reference doc
#     loc          - split from a real pre-punctuated LoC (MARC21) record
#     constructed  - made up to exercise the rules as written
#     not_handled  - a documented skip: [doc §X.Y #N - NOT HANDLED: reason]
#                    (added in the coverage pass; no render body)
#
# The examples carry no doc '#' (per-section example) numbering yet; that
# pin is added in the coverage pass (marker form [doc §X.Y #N]). Until then,
# 'num' is null and 'status' mirrors the provenance kind.
#
# Usage:
#   ./scripts/doc_coverage.pl [OUTFILE] [TESTFILE...]
#
# Sync check (to assert the table is up to date with the tests):
#   perl scripts/doc_coverage.pl && git diff --exit-code docs/doc_coverage.yaml
#
# Reads TestHelper from t/lib so marker parsing stays the single source of
# truth with the rest of the suite.

use strict;
use warnings;
use lib '.';
use lib 't/lib';
use t::lib::TestHelper qw( parse_render_marker );

my $outfile   = shift // 'docs/doc_coverage.yaml';
my @testfiles = @ARGV;
@testfiles = glob('t/*.t') unless @testfiles;

# --- Collect examples: field tag -> ordered list of { ... } ---
# Preserve source-file + original order; group later by tag.
my @collect;    # flat list of { tag, prov, marker, file }

for my $file (@testfiles) {
    open my $fh, '<', $file or die "Cannot read $file: $!\n";
    while ( my $line = <$fh> ) {
        next unless $line =~ /^\s*#\s*render:/;
        my $marker = $line;

        # Detect a NOT-HANDLED marker (no render body): line form
        #   # render: [doc §X.Y #N - NOT HANDLED: reason]
        if ( $marker =~ /\[(doc|LoC)\b[^\]]*\bNOT\s+HANDLED\b[^\]]*\]/i ) {
            my ($tok)   = $marker =~ /render:\s*(\[(?:doc|LoC)\b[^\]]*\])/i;
            my ($tag)   = $tok =~ /(?:doc|LoC)\b[^\]]*?\b([0-9]{3})\b/i
              ? $1 : '';
            my ($reason) = $marker =~ /-\s*NOT\s+HANDLED:\s*(.+?)\s*\]\s*$/i;
            push @collect, {
                tag      => $tag,
                kind     => 'not_handled',
                section  => '',
                derived  => 0,
                num      => undef,
                reason   => ( defined $reason ? $reason : '' ),
                marker   => $marker,
                file     => $file,
            };
            next;
        }

        my ( $prov, $tag, $ind1, $ind2, @subfields ) =
          parse_render_marker($marker);
        next unless defined $tag;

        my $kind = $prov->{kind} eq 'doc' ? 'doc'
          : $prov->{kind} eq 'LoC' ? 'loc'
          : 'constructed';

        # status: doc gets 'derived' when '- derived'; loc/constructed as-is
        my $status = $kind;
        $status = 'derived' if $kind eq 'doc' && $prov->{derived};

        push @collect, {
            tag      => $tag,
            kind     => $kind,
            status   => $status,
            section  => $prov->{section},
            derived  => $prov->{derived},
            num      => undef,
            reason   => '',
            marker   => $marker,
            file     => $file,
        };
    }
    close $fh;
}

# --- Group by tag, preserving first-seen order, keep original file order ---
my %order;
my @tags;
for my $e (@collect) {
    next unless length $e->{tag};
    if ( !exists $order{ $e->{tag} } ) {
        $order{ $e->{tag} } = 1;
        push @tags, $e->{tag};
    }
}
@tags = sort { $a <=> $b } @tags;

# --- Count summary by kind ---
my %bykind;
$bykind{ $_->{kind} }++ for @collect;

# --- Emit deterministic YAML ---
my @out;
push @out, '# GENERATED by scripts/doc_coverage.pl from the t/*.t "# render:"';
push @out, '# markers (the single source of truth). DO NOT EDIT BY HAND.';
push @out, '# Regenerate with: perl scripts/doc_coverage.pl';
push @out, '# Sync check:      perl scripts/doc_coverage.pl && git diff --exit-code docs/doc_coverage.yaml';
push @out, '';
push @out, 'meta:';
push @out, '  ruleset: "LoC/PCC"';
push @out, '  doc: "Revised Final Report PCC ISBD and MARC Task Group, October 2016"';
push @out, '  source: "t/*.t # render: markers (single source of truth)"';
push @out, '  generated_by: "scripts/doc_coverage.pl"';
push @out, '  notes: >-';
push @out, '    "num" (per-section example number) is null until the coverage pass';
push @out, '    pins each [doc §X.Y #N] marker; "status" mirrors kind until then.';
push @out, 'summary:';
push @out, '  total_examples: ' . scalar(@collect);
for my $k (qw(doc derived loc constructed not_handled)) {
    push @out, sprintf( '  %s: %d', $k, $bykind{$k} || 0 );
}
push @out, 'fields:';

for my $tag (@tags) {
    push @out, "  - tag: \"$tag\"";
    push @out, '    examples:';
    for my $e ( grep { $_->{tag} eq $tag } @collect ) {
        push @out, '      - doc: ' . ( $e->{section} ? qq{"$e->{section}"} : 'null' );
        push @out, '        num: ' . ( defined $e->{num} ? $e->{num} : 'null' );
        push @out, '        kind: ' . $e->{kind};
        push @out, '        status: ' . ( $e->{status} || $e->{kind} );
        push @out, '        derived: ' . ( $e->{derived} ? 'true' : 'false' );
        push @out, '        reason: ' . ( length $e->{reason} ? qq{"$e->{reason}"} : '""' );
        push @out, '        testfile: ' . qq{"$e->{file}"};
        # marker: prose one-liner (first line, trimmed) for human glance
        my $m = $e->{marker};
        $m =~ s/^\s+|\s+$//g;
        $m =~ s/\$\\/\\\$/g;    # keep \$ readable, avoid YAML-ambiguous
        push @out, '        marker: ' . qq{"$m"};
    }
}

open my $out, '>', $outfile or die "Cannot write $outfile: $!\n";
print {$out} join( "\n", @out ), "\n";
close $out;

print "Wrote $outfile (", scalar(@collect), " examples across ",
  scalar(@tags), " fields)\n";
